server:
  port: 8181

##FeignClient超时设置
spring:
  cloud:
    loadbalancer.retry.enabled: true
    ibbon.ConnectTimeout: 250
    ribbon.ReadTimeout: 1000
    ribbon.OkToRetryOnAllOperations: true
    ribbon.MaxAutoRetriesNextServer: 2
    ribbon.MaxAutoRetries: 1
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:a@172.20.85.24:7301/eureka
  instance:
    preferIpAddress: true
    instance-id: ifav-web-1
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30



