server:
  port: 8181

##FeignClient超时设置
spring:
  cloud:
    loadbalancer.retry.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon.ConnectTimeout: 250
ribbon.ReadTimeout: 1000
ribbon.OkToRetryOnAllOperations: true
ribbon.MaxAutoRetriesNextServer: 2
ribbon.MaxAutoRetries: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:a@172.18.50.169:7301/eureka
  instance:
    preferIpAddress: true
    instance-id: ifav-web-1
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30



